name: pokedex_with_riverpod
description: A new Flutter project.



publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'







dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.3
  shared_preferences: ^2.0.17
  state_notifier: ^0.7.2+1
  go_router: ^6.2.0
  palette_generator: ^0.3.3
  responsive_builder: ^0.4.2
  cached_network_image: ^3.2.0
  flutter_svg: ^1.0.3
  shimmer: ^2.0.0

dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0
  http_mock_adapter: ^0.4.2
  json_serializable: ^6.5.3
  mocktail: ^0.3.0
  state_notifier_test: ^0.0.9
  test_coverage_badge: ^0.2.0
  
  
  
  
  
  
  




flutter:

  
  
  
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
